# This Ansible playbook performs server preparation tasks
# Such as installing required packages, encrypting disks, and configuring the CPU.
---
- name: Update apt repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - cryptsetup
    - network-manager
    - linux-tools-{{ ansible_kernel }}

- name: Encrypt the second disk
  community.crypto.luks_device:
    name: "{{ second_disk }}"
    state: opened
    passphrase: "password"
  ignore_errors: true

- name: Encrypt the first disk's second partition
  community.crypto.luks_device:
    name: "{{ first_disk_second_partition }}"
    state: opened
    passphrase: "password"
  ignore_errors: true

- name: Disable C-states for all CPUs
  ansible.builtin.shell: echo 1 > /sys/devices/system/cpu/cpu{{ item }}/cpuidle/state{{ cstate }}/disable
  with_sequence: start=0 end={{ ansible_processor_count|int - 1 }}
  vars:
    cstate: 1
  become_user: root

- name: Check if cpufreq module is loaded
  block:
    - ansible.builtin.shell: lsmod | grep cpufreq
      register: cpufreq_module
      changed_when: false
  rescue:
    - name: Handle the error
      ansible.builtin.debug:
        msg: "Failed to check if cpufreq module is loaded"
      ignore_errors: true
      failed_when: false

- name: Switch CPU to performance mode
  ansible.builtin.shell: cpupower frequency-set --governor performance
  ignore_errors: true
  become_user: root
  when: cpufreq_module.rc == 0

- name: Rename network interface to net0
  community.general.nmcli:
    type: ethernet
    conn_name: net0
    ifname: "{{ ansible_default_ipv4.interface }}"
    state: present
  register: net_info

- name: Display network interface info
  ansible.builtin.debug:
    msg: "{{ net_info }}"

- name: Display CPU list and Hyper-Threading information
  ansible.builtin.shell: lscpu
  register: cpu_info

- name: Show CPU info
  ansible.builtin.debug:
    var: cpu_info.stdout
